package com.fieldstack.android.domain.usecase

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import com.fieldstack.android.domain.model.Report
import dagger.hilt.android.qualifiers.ApplicationContext
import java.io.File
import java.time.ZoneId
import java.time.format.DateTimeFormatter
import javax.inject.Inject

class PdfExportUseCase @Inject constructor(
    @ApplicationContext private val ctx: Context,
) {
    private val dtFmt = DateTimeFormatter.ofPattern("MMM d, yyyy h:mm a")
        .withZone(ZoneId.systemDefault())

    /** Renders [report] to a PDF file in the app's files dir. Returns the file. */
    operator fun invoke(report: Report): File {
        val doc = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4 pts
        val page = doc.startPage(pageInfo)
        draw(page.canvas, report)
        doc.finishPage(page)

        val file = File(ctx.filesDir, "report_${report.id}.pdf")
        file.outputStream().use { doc.writeTo(it) }
        doc.close()
        return file
    }

    private fun draw(canvas: Canvas, report: Report) {
        val titlePaint = Paint().apply { color = Color.parseColor("#10B981"); textSize = 22f; isFakeBoldText = true }
        val headPaint  = Paint().apply { color = Color.parseColor("#1C1917"); textSize = 14f; isFakeBoldText = true }
        val bodyPaint  = Paint().apply { color = Color.parseColor("#57534E"); textSize = 12f }
        val mutedPaint = Paint().apply { color = Color.parseColor("#78716C"); textSize = 10f }

        var y = 60f
        fun line(text: String, paint: Paint, indent: Float = 40f) {
            canvas.drawText(text, indent, y, paint); y += paint.textSize + 8f
        }
        fun gap(n: Float = 12f) { y += n }

        line("FieldStack Report", titlePaint)
        gap()
        line(report.title, headPaint)
        line("Category: ${report.category.name}  ·  Created: ${dtFmt.format(report.createdAt)}", mutedPaint)
        gap()
        line("Findings", headPaint)
        // Word-wrap details at ~70 chars
        report.details.chunked(70).forEach { line(it, bodyPaint) }
        gap()
        if (report.photoUris.isNotEmpty()) {
            line("Photos: ${report.photoUris.size} attached", mutedPaint)
            gap()
        }
        if (report.latitude != null && report.longitude != null) {
            line("Location: %.4f°, %.4f°".format(report.latitude, report.longitude), mutedPaint)
            gap()
        }
        line("Signature: ${if (report.signatureUri != null) "Signed" else "Not signed"}", mutedPaint)
        gap(20f)
        line("— Generated by FieldStack Android 0.1.0-mvp", mutedPaint)
    }
}
